name: intl_phone_field_v2
description: A customised Flutter TextFormField to input international phone number along with country code, flag, dial code, validation and currency information.
version: 4.0.5
homepage: https://github.com/sabikrahat/intl_phone_field_v2
repository: https://github.com/sabikrahat/intl_phone_field_v2
issue_tracker: https://github.com/sabikrahat/intl_phone_field_v2/issues

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/
