name: intl_phone_field_v2
description: A customised Flutter TextFormField to input international phone number along with country code, flag, dial code, validation and currency information.
version: 4.0.2
homepage: https://github.com/sabikrahat/intl_phone_field_v2
repository: https://github.com/sabikrahat/intl_phone_field_v2
issue_tracker: https://github.com/sabikrahat/intl_phone_field_v2/issues

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.15

flutter:
  assets:
    - assets/flags/
